version: '3'
services:
  mysql-db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spring_boot_database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3308:3306

  app:
    build: .
    image: app:latest
    ports:
       - 8080:8080
    depends_on:
       - mysql-db